/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defense.system;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author DELL
 */
public class Maincontraller extends javax.swing.JFrame{

    public Maincontraller(){
    
    }
    
    public DSObservable dSObservable;
    
    public Maincontraller(DSObservable dSObservable){
        this.dSObservable = dSObservable;
        initComponents();
        setTitle("Maincontraller");
        setLocation(50,20);
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        comboboxmaincontraller = new javax.swing.JComboBox<>();
        collectinfo = new javax.swing.JButton();
        areaClear = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Sliderposition = new javax.swing.JSlider();
        jCheckBox2 = new javax.swing.JCheckBox();
        btnSend = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreamessagebox = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        TextAreamsg = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtmessagebox = new javax.swing.JTextArea();
        soldiertxt = new javax.swing.JTextField();
        fueltxt = new javax.swing.JTextField();
        ammotxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboboxmaincontraller.setBackground(new java.awt.Color(153, 153, 153));
        comboboxmaincontraller.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboboxmaincontraller.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select defence", "hellicopter", "tank", "submarine" }));
        comboboxmaincontraller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxmaincontrallerActionPerformed(evt);
            }
        });
        comboboxmaincontraller.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                comboboxmaincontrallerPropertyChange(evt);
            }
        });
        getContentPane().add(comboboxmaincontraller, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        collectinfo.setBackground(new java.awt.Color(153, 153, 153));
        collectinfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        collectinfo.setText("Collect information");
        collectinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectinfoActionPerformed(evt);
            }
        });
        getContentPane().add(collectinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 6, -1, -1));

        areaClear.setBackground(new java.awt.Color(204, 204, 204));
        areaClear.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        areaClear.setText("Area clear");
        areaClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaClearActionPerformed(evt);
            }
        });
        getContentPane().add(areaClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 7, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Soldier count");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fuel amount");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ammo amount");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Position");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 126, -1, -1));

        Sliderposition.setMajorTickSpacing(20);
        Sliderposition.setMinorTickSpacing(10);
        Sliderposition.setPaintLabels(true);
        Sliderposition.setPaintTicks(true);
        Sliderposition.setToolTipText("");
        Sliderposition.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Sliderposition.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderpositionStateChanged(evt);
            }
        });
        getContentPane().add(Sliderposition, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 148, 275, 60));

        jCheckBox2.setBackground(new java.awt.Color(204, 204, 204));
        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox2.setText("Send private");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 154, -1, -1));

        btnSend.setBackground(new java.awt.Color(204, 204, 204));
        btnSend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        getContentPane().add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 153, -1, -1));

        txtAreamessagebox.setBackground(new java.awt.Color(204, 204, 204));
        txtAreamessagebox.setColumns(20);
        txtAreamessagebox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAreamessagebox.setRows(5);
        txtAreamessagebox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane4.setViewportView(txtAreamessagebox);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 34, 170, -1));

        TextAreamsg.setBackground(new java.awt.Color(204, 204, 204));
        TextAreamsg.setColumns(20);
        TextAreamsg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TextAreamsg.setRows(5);
        jScrollPane5.setViewportView(TextAreamsg);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 214, 170, -1));

        txtmessagebox.setBackground(new java.awt.Color(204, 204, 204));
        txtmessagebox.setColumns(20);
        txtmessagebox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtmessagebox.setRows(5);
        jScrollPane1.setViewportView(txtmessagebox);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 214, 182, -1));

        soldiertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soldiertxtActionPerformed(evt);
            }
        });
        getContentPane().add(soldiertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 34, 36, -1));
        getContentPane().add(fueltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 62, 36, -1));
        getContentPane().add(ammotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 90, 36, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interior-old-military-ship-night-3d-rendering-control-room-shipwreck-ai-generated_538213-34698 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxmaincontrallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxmaincontrallerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxmaincontrallerActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        String message = txtAreamessagebox.getText();
        dSObservable.setUpdateSendMessage(message);
    }//GEN-LAST:event_btnSendActionPerformed

    private void areaClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaClearActionPerformed
        // TODO add your handling code here:
        areaClear.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
               boolean select = areaClear.isSelected();
               if(select == true){
                   dSObservable.setAreaClearedMessage(true);
               }else{
                   dSObservable.setAreaClearedMessage(false);
               }
            }
        });
    }//GEN-LAST:event_areaClearActionPerformed

    private void SliderpositionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderpositionStateChanged
        Sliderposition.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                dSObservable.setUpdatePosition(Sliderposition.getValue());
            }
        });
    }//GEN-LAST:event_SliderpositionStateChanged

    private void comboboxmaincontrallerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_comboboxmaincontrallerPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxmaincontrallerPropertyChange

    private void soldiertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soldiertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soldiertxtActionPerformed

    private void collectinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectinfoActionPerformed
        // TODO add your handling code here:
        int dropDown = this.comboboxmaincontraller.getSelectedIndex();
        System.out.println(dropDown);
        if (dropDown == 1){
            
                String soldierCount = Helicopter.Spinnersoldier.getValue().toString();
                String ammoCount = Helicopter.Spinnerammo.getValue().toString();
                int fuelAmount = Helicopter.helislider.getValue();
                soldiertxt.setText(" "+soldierCount);
                ammotxt.setText(" "+ammoCount);
                fueltxt.setText(" "+fuelAmount);
                TextAreamsg.setText("");
        }else if (dropDown == 3){
            
                String soldierCount = Submarine.Spinnersoldier.getValue().toString();
                String ammoCount = Submarine.Spinnerammo.getValue().toString();
                int fuelAmount = Submarine.subSlider.getValue();
                int oxygenLevel = Submarine.subSlideroxy.getValue();
                soldiertxt.setText(" "+soldierCount);
                ammotxt.setText(" "+ammoCount);
                fueltxt.setText(" "+fuelAmount);
                TextAreamsg.setText("OxygenLevel :"+oxygenLevel);
        }else if(dropDown == 2){
                String soldierCount = Tank.Spinnersoldier.getValue().toString();
                String ammoCount = Tank.Spinnerammo.getValue().toString();
                int fuelAmount = Tank.tankSlider.getValue();
                soldiertxt.setText(" "+soldierCount);
                ammotxt.setText(" "+ammoCount);
                fueltxt.setText(" "+fuelAmount);
                TextAreamsg.setText("");
        }
        
    }//GEN-LAST:event_collectinfoActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maincontraller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maincontraller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maincontraller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maincontraller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maincontraller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider Sliderposition;
    private javax.swing.JTextArea TextAreamsg;
    private javax.swing.JTextField ammotxt;
    private javax.swing.JCheckBox areaClear;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton collectinfo;
    private javax.swing.JComboBox<String> comboboxmaincontraller;
    private javax.swing.JTextField fueltxt;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField soldiertxt;
    private javax.swing.JTextArea txtAreamessagebox;
    public static javax.swing.JTextArea txtmessagebox;
    // End of variables declaration//GEN-END:variables
}
