/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defense.system;

/**
 *
 * @author DELL
 */
public class Submarine extends javax.swing.JFrame implements DSObserver {

    /**
     * Creates new form Submarine
     */
    public DSObservable dSObsevable;
    public Submarine() {
        initComponents();
        setTitle("Submarine");
        setLocation(650,350);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shoot = new javax.swing.JButton();
        tomhaw = new javax.swing.JButton();
        sonarop = new javax.swing.JButton();
        trdmis = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Spinnersoldier = new javax.swing.JSpinner();
        Spinnerammo = new javax.swing.JSpinner();
        subSlideroxy = new javax.swing.JSlider();
        sendtextfield = new javax.swing.JTextField();
        sendbtn = new javax.swing.JButton();
        positioncheck = new javax.swing.JCheckBox();
        subSlider = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgTxtArea = new javax.swing.JTextArea();
        lblActionSub = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shoot.setBackground(new java.awt.Color(153, 153, 153));
        shoot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        shoot.setText("Shoot");
        shoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shootActionPerformed(evt);
            }
        });
        getContentPane().add(shoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, -1));

        tomhaw.setBackground(new java.awt.Color(153, 153, 153));
        tomhaw.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tomhaw.setText("Tomhawk Missile");
        tomhaw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomhawActionPerformed(evt);
            }
        });
        getContentPane().add(tomhaw, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, -1));

        sonarop.setBackground(new java.awt.Color(153, 153, 153));
        sonarop.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sonarop.setText("Sonar Operation");
        getContentPane().add(sonarop, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        trdmis.setBackground(new java.awt.Color(153, 153, 153));
        trdmis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        trdmis.setText("Trident-2 Missile");
        getContentPane().add(trdmis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ammo count");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 62, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Soldier count");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 62, -1));
        getContentPane().add(Spinnersoldier, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 58, -1));
        getContentPane().add(Spinnerammo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 58, -1));

        subSlideroxy.setBackground(new java.awt.Color(153, 153, 153));
        subSlideroxy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subSlideroxy.setMajorTickSpacing(20);
        subSlideroxy.setMinorTickSpacing(10);
        subSlideroxy.setOrientation(javax.swing.JSlider.VERTICAL);
        subSlideroxy.setPaintLabels(true);
        subSlideroxy.setPaintTicks(true);
        subSlideroxy.setToolTipText("");
        subSlideroxy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(subSlideroxy, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 31, 57, 201));

        sendtextfield.setBackground(new java.awt.Color(204, 204, 204));
        sendtextfield.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sendtextfield.setText(" ");
        sendtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendtextfieldActionPerformed(evt);
            }
        });
        getContentPane().add(sendtextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 282, -1));

        sendbtn.setBackground(new java.awt.Color(204, 204, 204));
        sendbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sendbtn.setText("send");
        sendbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendbtnActionPerformed(evt);
            }
        });
        getContentPane().add(sendbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        positioncheck.setBackground(new java.awt.Color(204, 204, 204));
        positioncheck.setText("Position");
        positioncheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positioncheckActionPerformed(evt);
            }
        });
        getContentPane().add(positioncheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        subSlider.setBackground(new java.awt.Color(153, 153, 153));
        subSlider.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subSlider.setMajorTickSpacing(20);
        subSlider.setMinorTickSpacing(10);
        subSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        subSlider.setPaintLabels(true);
        subSlider.setPaintTicks(true);
        subSlider.setToolTipText("");
        subSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(subSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 31, 57, 201));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Energy");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 6, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Oxygen");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 6, -1, -1));

        msgTxtArea.setBackground(new java.awt.Color(204, 204, 204));
        msgTxtArea.setColumns(20);
        msgTxtArea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        msgTxtArea.setRows(5);
        jScrollPane1.setViewportView(msgTxtArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 351, 123));

        lblActionSub.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblActionSub.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblActionSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 19));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/submarines-army-water-war-ship_635335-343 (2).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shootActionPerformed

    private void tomhawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomhawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tomhawActionPerformed

    private void sendtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendtextfieldActionPerformed

    private void sendbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendbtnActionPerformed
        // TODO add your handling code here:
        Maincontraller maincontraller = new Maincontraller();
        String message = sendtextfield.getText();
        Maincontraller.txtmessagebox.append("\nSubmarine :"+message);
    }//GEN-LAST:event_sendbtnActionPerformed

    private void positioncheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positioncheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positioncheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Submarine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JSpinner Spinnerammo;
    public static javax.swing.JSpinner Spinnersoldier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActionSub;
    private javax.swing.JTextArea msgTxtArea;
    private javax.swing.JCheckBox positioncheck;
    private javax.swing.JButton sendbtn;
    private javax.swing.JTextField sendtextfield;
    private javax.swing.JButton shoot;
    private javax.swing.JButton sonarop;
    public static javax.swing.JSlider subSlider;
    public static javax.swing.JSlider subSlideroxy;
    private javax.swing.JButton tomhaw;
    private javax.swing.JButton trdmis;
    // End of variables declaration//GEN-END:variables

    @Override
    public void areaClearedMessage(boolean status) {
        if (status == true) {
            lblActionSub.setText("Cleared");
        } else if (status == false) {
            lblActionSub.setText("Area Not Cleared");
        }
    }
    
    @Override
    public void updatePosition(int positionLevel) {

        if (positioncheck.isSelected() == true) {
            if (positionLevel > 20) {
                shoot.setEnabled(true);
            } else {
                shoot.setEnabled(false);
            }
            if (positionLevel > 40) {
                sonarop.setEnabled(true);
            } else {
                sonarop.setEnabled(false);
            }
            if (positionLevel > 60) {
                tomhaw.setEnabled(true);
            } else {
                tomhaw.setEnabled(false);
            }
            if (positionLevel > 80) {
                trdmis.setEnabled(true);
            } else {
                trdmis.setEnabled(false);
            }
        } else {
            shoot.setEnabled(false);
            sonarop.setEnabled(false);
            tomhaw.setEnabled(false);
            trdmis.setEnabled(false);
        }
    }
    @Override
    public void updateSendMessage(String message) {
        msgTxtArea.setText(message);
    }
}

