/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defense.system;

/**
 *
 * @author DELL
 */
public class Tank extends javax.swing.JFrame implements DSObserver{

    /**
     * Creates new form Tank
     */
    public Tank() {
        initComponents();
        setTitle("Tank");
        setLocation(650,20);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendtxtfield = new javax.swing.JTextField();
        btnsend = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Spinnersoldier = new javax.swing.JSpinner();
        tankSlider = new javax.swing.JSlider();
        Spinnerammo = new javax.swing.JSpinner();
        lblaction1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        shoot = new javax.swing.JButton();
        misop = new javax.swing.JButton();
        laserop = new javax.swing.JButton();
        rotateshoot = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        messagetextarea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sendtxtfield.setBackground(new java.awt.Color(204, 204, 204));
        sendtxtfield.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sendtxtfield.setText(" ");
        sendtxtfield.setBorder(null);
        sendtxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendtxtfieldActionPerformed(evt);
            }
        });
        getContentPane().add(sendtxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 282, -1));

        btnsend.setBackground(new java.awt.Color(204, 204, 204));
        btnsend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsend.setText("Send");
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });
        getContentPane().add(btnsend, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Soldier count");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 62, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ammo count");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 62, -1));

        Spinnersoldier.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinnersoldierStateChanged(evt);
            }
        });
        getContentPane().add(Spinnersoldier, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 58, -1));

        tankSlider.setBackground(new java.awt.Color(153, 153, 153));
        tankSlider.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        tankSlider.setMajorTickSpacing(20);
        tankSlider.setMinorTickSpacing(10);
        tankSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        tankSlider.setPaintLabels(true);
        tankSlider.setPaintTicks(true);
        tankSlider.setToolTipText("");
        tankSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(tankSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 15, 57, 225));
        getContentPane().add(Spinnerammo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 58, -1));

        lblaction1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblaction1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblaction1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 120, 16));

        jCheckBox1.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox1.setText("Position");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 99, 85, -1));

        shoot.setBackground(new java.awt.Color(153, 153, 153));
        shoot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        shoot.setText("Shoot");
        shoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shootActionPerformed(evt);
            }
        });
        getContentPane().add(shoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 120, -1));

        misop.setBackground(new java.awt.Color(153, 153, 153));
        misop.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        misop.setText("Missile Operation");
        misop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misopActionPerformed(evt);
            }
        });
        getContentPane().add(misop, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        laserop.setBackground(new java.awt.Color(153, 153, 153));
        laserop.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        laserop.setText("Laser Operation");
        laserop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laseropActionPerformed(evt);
            }
        });
        getContentPane().add(laserop, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, -1));

        rotateshoot.setBackground(new java.awt.Color(153, 153, 153));
        rotateshoot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rotateshoot.setText("Rotate Shooting");
        getContentPane().add(rotateshoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 122, -1));

        messagetextarea.setBackground(new java.awt.Color(204, 204, 204));
        messagetextarea.setColumns(20);
        messagetextarea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        messagetextarea.setRows(5);
        messagetextarea.setBorder(null);
        jScrollPane1.setViewportView(messagetextarea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 351, 123));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dark-style-war-tank-battlefield (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendtxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendtxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendtxtfieldActionPerformed

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
        // TODO add your handling code here:
        Maincontraller maincontraller = new Maincontraller();
        String message = sendtxtfield.getText();
        Maincontraller.txtmessagebox.append("\nTank :"+message);
    }//GEN-LAST:event_btnsendActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void shootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shootActionPerformed

    private void laseropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laseropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laseropActionPerformed

    private void misopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_misopActionPerformed

    private void SpinnersoldierStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinnersoldierStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_SpinnersoldierStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JSpinner Spinnerammo;
    public static javax.swing.JSpinner Spinnersoldier;
    private javax.swing.JButton btnsend;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton laserop;
    private javax.swing.JLabel lblaction1;
    private javax.swing.JTextArea messagetextarea;
    private javax.swing.JButton misop;
    private javax.swing.JButton rotateshoot;
    private javax.swing.JTextField sendtxtfield;
    private javax.swing.JButton shoot;
    public static javax.swing.JSlider tankSlider;
    // End of variables declaration//GEN-END:variables
    @Override
    public void areaClearedMessage(boolean status) {
        if (status == true) {
            lblaction1.setText("Cleared");
        } else if (status == false) {
            lblaction1.setText("Area Not Cleared");
        }
    }
    @Override
    public void updatePosition(int positionLevel) {

        if (jCheckBox1.isSelected() == true) {
            if (positionLevel > 20) {
                shoot.setEnabled(true);
            } else {
                shoot.setEnabled(false);
            }
            if (positionLevel > 40) {
                misop.setEnabled(true);
            } else {
                misop.setEnabled(false);
            }
            if (positionLevel > 60) {
                laserop.setEnabled(true);
            } else {
                laserop.setEnabled(false);
            }
            if (positionLevel > 80) {
                rotateshoot.setEnabled(true);
            } else {
                rotateshoot.setEnabled(false);
            }
        } else {
            shoot.setEnabled(false);
            misop.setEnabled(false);
            laserop.setEnabled(false);
            rotateshoot.setEnabled(false);
        }
    }
    
    public void updateSendMessage(String message) {
//        if(select == true && checkNum == 1){
//        messagetextarea.setText("Private Message : \n\t"+ message);
//        }else{
        messagetextarea.setText(message);
        }
    }


